# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae9fafd28ff1313cebd95e37b0be50a357dc3fb70b318e10fa8da2cc2543ff53460ac3b370dcfda8c13e31647eec61425adf5c6db9f6c836d03446ceec36bb9c

test:
  secret_key_base: 102a325fc1d7c5e5459215e2a18269f66260392cfb6f615949e40be5aa1559a4a4e24b7db6b1b3a6782d4cad8a85c1df1ff07c8532f6dcb05b3e4d42d19ef2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
